import type { Config } from "tailwindcss";

// Design tokens portados VERBATIM da config Tailwind dos mockups
// (sistema/front/*/code.html) para preservar 100% da fidelidade visual.
// Fonte: DESIGN.md (Gevi-Inspired Financial Identity) — paleta navy/cyan,
// tipografia Hanken Grotesk, cantos arredondados, espaçamento em base 4px.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#bac9d3",
        surface: "#f7fafc",
        "secondary-container": "#2dbcfe",
        "surface-dim": "#d7dadc",
        "on-tertiary-fixed-variant": "#3b4951",
        "on-primary-fixed": "#001a3f",
        "surface-variant": "#e0e3e5",
        primary: "#000000",
        secondary: "#00658d",
        "secondary-fixed-dim": "#82cfff",
        "on-error": "#ffffff",
        "primary-container": "#001a3f",
        "outline-variant": "#c4c6cf",
        "on-tertiary-fixed": "#0f1d25",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e5e9eb",
        "on-tertiary-container": "#778690",
        "on-tertiary": "#ffffff",
        "surface-container": "#ebeef0",
        "primary-fixed-dim": "#b2c7f5",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef1f3",
        "tertiary-fixed": "#d6e5ef",
        "inverse-surface": "#2d3133",
        "surface-tint": "#4a5e87",
        "on-background": "#181c1e",
        background: "#f7fafc",
        "on-secondary-container": "#004866",
        "on-surface-variant": "#44474e",
        "primary-fixed": "#d7e2ff",
        "surface-container-low": "#f1f4f6",
        "on-secondary-fixed-variant": "#004c6b",
        "error-container": "#ffdad6",
        "surface-bright": "#f7fafc",
        "on-secondary": "#ffffff",
        "on-surface": "#181c1e",
        "inverse-primary": "#b2c7f5",
        "on-secondary-fixed": "#001e2d",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#c6e7ff",
        tertiary: "#000000",
        outline: "#74777f",
        "on-primary-fixed-variant": "#32476d",
        "on-primary-container": "#6f84ae",
        "tertiary-container": "#0f1d25",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        sm: "16px",
        lg: "32px",
        gutter: "20px",
        "container-max": "1440px",
        xl: "48px",
        base: "4px",
        xs: "8px",
      },
      fontFamily: {
        "data-display": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
      },
      fontSize: {
        "data-display": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};

export default config;
